/**
 * Component barrel exports
 *
 * Most components re-export from @kingly/ui (canonical source).
 * Runtime-coupled components (SharedComponents, EnrichmentPanel) remain local.
 */

// Runtime-coupled — stay local (depend on @agentping/core)
export { ApprovalButtons, QuestionInput, DirectionPicker, NotificationBanner } from './SharedComponents';
export { EnrichmentPanel, QuickActionBar } from './EnrichmentPanel';

// Conflict-family wrappers — stay local (adapter layer)
export { Badge } from './Badge';
export { CodeDiffViewer } from './CodeDiffViewer';
export { ContextMenu } from './ContextMenu';
export { EmptyState } from './EmptyState';
export { LogViewer } from './LogViewer';
export { SearchInput } from './SearchInput';
export { Spinner } from './Spinner';
export { Timeline } from './Timeline';

// All other components — direct re-export from @kingly/ui
export {
    PingCard,
    StepChecklist,
    SelectionList,
    HistoryView,
    TaskWorkflow,
    PrimitivesGallery,
    DependencyGraph,
    StatusCard,
    ProgressTimeline,
    InfoSidebar,
    InlineTutorialTooltip,
    FileAssetPicker,
    ConfirmationModal,
    LoadingProgress,
    RichMarkdownRenderer,
    ProgressBar,
    StatusIndicator,
    StepTracker,
    LiveBadge,
    ConnectionSignal,
    BatteryMeter,
    TypingIndicator,
    ErrorBoundary,
    TokenStream,
    ConfidenceMeter,
    ModelSelector,
    ContextUsage,
    PromptEditor,
    AgentAvatar,
    MessageBubble,
    BrainActivity,
    ToolInvocation,
    VectorCluster,
    WorldClock,
    WeatherCard,
    DataTable,
    SecretInput,
    JsonEditor,
    ImageDiff,
    TerminalView,
    TreeBrowser,
    TabsContainer,
    MetricChart,
    WizardStep,
    KanbanBoard,
    HeatmapGrid,
    AudioPlayer,
    VideoPlayer,
    CommandPalette,
    PropertyGrid,
    StatsGrid,
    CalendarView,
    AccordionList,
    Breadcrumbs,
    ToastManager,
    AlertBanner,
    Skeleton,
    CircularProgress,
    ToggleSwitch,
    Slider,
    MultiSelect,
    TextArea,
    LandingPage,
    LogStream,
    ResourceGauge,
    QuickActions,
    HoverCard,
    DraggableList,
    MiniMap,
    Pagination,
    SplitView,
    Stepper,
    RadarChart,
    SankeyDiagram,
    NetworkGraph,
    OrgChart,
    MindMap,
    RadialNav,
    DockMenu,
    SidePanel,
    ActivityFeed,
    TeamRoster,
    TaskQueue,
    ColorPicker,
    DatePicker,
    RangeSlider,
    PinInput,
    Rating,
    TransferList,
    EditableText,
    Knob,
    SegmentedControl,
    TagInput,
    NetworkTopology,
    LogHistogram,
    SystemHealthGauge,
    MemoryUsageChart,
    GeoRequestMap,
    StorageDistribution,
    LatencyHistogram,
    ErrorCluster,
    ActiveSessions,
    AuditLogViewer,
    JsonDiff,
    HexInspector,
    MarkdownEditor,
    ImageCompare,
    CsvViewer,
    PdfPreview,
    ConflictResolver,
    DiffStatSummary,
    FileMetadataCard,
    RegexTester,
    WeeklySchedule,
    DailyAgenda,
    EventCard,
    DatePickerPro,
    TimeSlotPicker,
    ResourceView,
    YearHeatmap,
    TimezoneSlider,
    CountdownWidget,
    RecurringEventEditor,
    LeaseApproval,
} from '@kingly/ui/components';
