// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/assets/dot-amber.png"
    | "/assets/dot-amber.svg"
    | "/assets/dot-cyan.png"
    | "/assets/dot-cyan.svg"
    | "/assets/dot-gray.png"
    | "/assets/dot-gray.svg"
    | "/assets/dot-green.png"
    | "/assets/dot-green.svg"
    | "/background.js"
    | "/content-scripts/content.js"
    | "/popup.html"
    | "/webmcp-content.js"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
