import type { ComponentMeta, Domain, GateStatus } from "./types";

/**
 * Pass 5 Component Manifest
 *
 * Representative subset of the 327 catalog components.
 * Includes all 11 conflict families, 20 REAL, 5 SHELL, and 5 HOLLOW entries.
 */
export const COMPONENT_MANIFEST: Record<string, ComponentMeta> = {
  // ---------------------------------------------------------------------------
  // CONFLICT FAMILIES (11)
  // ---------------------------------------------------------------------------
  "badge-conflict": {
    id: "badge-conflict",
    name: "Badge",
    family: "foundations/badges-labels",
    domain: "shared",
    lanes: ["agentping", "sophia", "combined"],
    beadId: "ap-4rs.1",
    storyPath: "Catalog/Conflicts/Badge",
    gateStatus: "pass",
    classification: "REAL",
    markers: ["conflict"],
  },
  "button-conflict": {
    id: "button-conflict",
    name: "Button",
    family: "foundations/buttons",
    domain: "shared",
    lanes: ["agentping", "sophia", "combined"],
    beadId: "ap-4rs.2",
    storyPath: "Catalog/Conflicts/Button",
    gateStatus: "pass",
    classification: "REAL",
    markers: ["conflict"],
  },
  "code-diff-viewer-conflict": {
    id: "code-diff-viewer-conflict",
    name: "CodeDiffViewer",
    family: "foundations/data-display",
    domain: "shared",
    lanes: ["agentping", "sophia", "combined"],
    beadId: "ap-4rs.3",
    storyPath: "Catalog/Conflicts/CodeDiffViewer",
    gateStatus: "pass",
    classification: "REAL",
    markers: ["conflict"],
  },
  "context-menu-conflict": {
    id: "context-menu-conflict",
    name: "ContextMenu",
    family: "foundations/navigation",
    domain: "shared",
    lanes: ["agentping", "sophia", "combined"],
    beadId: "ap-4rs.4",
    storyPath: "Catalog/Conflicts/ContextMenu",
    gateStatus: "pass",
    classification: "REAL",
    markers: ["conflict"],
  },
  "empty-state-conflict": {
    id: "empty-state-conflict",
    name: "EmptyState",
    family: "foundations/feedback-status",
    domain: "shared",
    lanes: ["agentping", "sophia", "combined"],
    beadId: "ap-4rs.5",
    storyPath: "Catalog/Conflicts/EmptyState",
    gateStatus: "pass",
    classification: "REAL",
    markers: ["conflict"],
  },
  "icon-button-conflict": {
    id: "icon-button-conflict",
    name: "IconButton",
    family: "foundations/buttons",
    domain: "shared",
    lanes: ["agentping", "sophia", "combined"],
    beadId: "ap-4rs.6",
    storyPath: "Catalog/Conflicts/IconButton",
    gateStatus: "pass",
    classification: "REAL",
    markers: ["conflict"],
  },
  "input-conflict": {
    id: "input-conflict",
    name: "Input",
    family: "foundations/forms",
    domain: "shared",
    lanes: ["agentping", "sophia", "combined"],
    beadId: "ap-4rs.7",
    storyPath: "Catalog/Conflicts/Input",
    gateStatus: "pass",
    classification: "REAL",
    markers: ["conflict"],
  },
  "search-input-conflict": {
    id: "search-input-conflict",
    name: "SearchInput",
    family: "foundations/forms",
    domain: "shared",
    lanes: ["agentping", "sophia", "combined"],
    beadId: "ap-4rs.8",
    storyPath: "Catalog/Conflicts/SearchInput",
    gateStatus: "pass",
    classification: "REAL",
    markers: ["conflict"],
  },
  "spinner-conflict": {
    id: "spinner-conflict",
    name: "Spinner",
    family: "foundations/feedback-status",
    domain: "shared",
    lanes: ["agentping", "sophia", "combined"],
    beadId: "ap-4rs.9",
    storyPath: "Catalog/Conflicts/Spinner",
    gateStatus: "pass",
    classification: "REAL",
    markers: ["conflict"],
  },
  "timeline-conflict": {
    id: "timeline-conflict",
    name: "Timeline",
    family: "foundations/data-display",
    domain: "shared",
    lanes: ["agentping", "sophia", "combined"],
    beadId: "ap-4rs.10",
    storyPath: "Catalog/Conflicts/Timeline",
    gateStatus: "pass",
    classification: "REAL",
    markers: ["conflict"],
  },
  "log-viewer-conflict": {
    id: "log-viewer-conflict",
    name: "LogViewer",
    family: "domain/logs",
    domain: "shared",
    lanes: ["agentping", "sophia", "combined"],
    beadId: "ap-4rs.11",
    storyPath: "Catalog/Conflicts/LogViewer",
    gateStatus: "pass",
    classification: "REAL",
    markers: ["conflict"],
  },

  // ---------------------------------------------------------------------------
  // REAL COMPONENTS (20 representative)
  // ---------------------------------------------------------------------------
  "activity-feed": {
    id: "activity-feed",
    name: "ActivityFeed",
    family: "foundations/feedback-status",
    domain: "webui",
    lanes: ["agentping"],
    beadId: "ap-4rs.20",
    storyPath: "Catalog/WebUI/ActivityFeed",
    gateStatus: "pass",
    classification: "REAL",
    markers: [],
  },
  "data-table": {
    id: "data-table",
    name: "DataTable",
    family: "foundations/data-display",
    domain: "webui",
    lanes: ["agentping"],
    beadId: "ap-4rs.21",
    storyPath: "Catalog/WebUI/DataTable",
    gateStatus: "pass",
    classification: "REAL",
    markers: [],
  },
  "agent-avatar": {
    id: "agent-avatar",
    name: "AgentAvatar",
    family: "foundations/badges-labels",
    domain: "webui",
    lanes: ["agentping"],
    beadId: "ap-4rs.22",
    storyPath: "Catalog/WebUI/AgentAvatar",
    gateStatus: "pass",
    classification: "REAL",
    markers: [],
  },
  "chat-panel": {
    id: "chat-panel",
    name: "ChatPanel",
    family: "domain/chat",
    domain: "webui",
    lanes: ["agentping"],
    beadId: "ap-4rs.23",
    storyPath: "Catalog/WebUI/ChatPanel",
    gateStatus: "pass",
    classification: "REAL",
    markers: [],
  },
  "terminal": {
    id: "terminal",
    name: "Terminal",
    family: "domain/logs",
    domain: "webui",
    lanes: ["agentping"],
    beadId: "ap-4rs.24",
    storyPath: "Catalog/WebUI/Terminal",
    gateStatus: "pass",
    classification: "REAL",
    markers: [],
  },
  "kanban-board": {
    id: "kanban-board",
    name: "KanbanBoard",
    family: "domain/data-display",
    domain: "webui",
    lanes: ["agentping"],
    beadId: "ap-4rs.25",
    storyPath: "Catalog/WebUI/KanbanBoard",
    gateStatus: "pass",
    classification: "REAL",
    markers: [],
  },
  "command-palette": {
    id: "command-palette",
    name: "CommandPalette",
    family: "foundations/navigation",
    domain: "webui",
    lanes: ["agentping"],
    beadId: "ap-4rs.26",
    storyPath: "Catalog/WebUI/CommandPalette",
    gateStatus: "pass",
    classification: "REAL",
    markers: [],
  },
  "approval-queue": {
    id: "approval-queue",
    name: "ApprovalQueue",
    family: "domain/crud",
    domain: "webui",
    lanes: ["agentping"],
    beadId: "ap-4rs.27",
    storyPath: "Catalog/WebUI/ApprovalQueue",
    gateStatus: "pass",
    classification: "REAL",
    markers: ["crud"],
  },
  "network-topology": {
    id: "network-topology",
    name: "NetworkTopology",
    family: "domain/system",
    domain: "webui",
    lanes: ["agentping"],
    beadId: "ap-4rs.28",
    storyPath: "Catalog/WebUI/NetworkTopology",
    gateStatus: "pass",
    classification: "REAL",
    markers: [],
  },
  "status-card": {
    id: "status-card",
    name: "StatusCard",
    family: "foundations/feedback-status",
    domain: "webui",
    lanes: ["agentping"],
    beadId: "ap-4rs.29",
    storyPath: "Catalog/WebUI/StatusCard",
    gateStatus: "pass",
    classification: "REAL",
    markers: [],
  },
  "candlestick-chart": {
    id: "candlestick-chart",
    name: "CandlestickChart",
    family: "domain/finance",
    domain: "webui",
    lanes: ["agentping"],
    beadId: "ap-4rs.30",
    storyPath: "Catalog/WebUI/CandlestickChart",
    gateStatus: "pass",
    classification: "REAL",
    markers: [],
  },
  "markdown-editor": {
    id: "markdown-editor",
    name: "MarkdownEditor",
    family: "domain/content",
    domain: "webui",
    lanes: ["agentping"],
    beadId: "ap-4rs.31",
    storyPath: "Catalog/WebUI/MarkdownEditor",
    gateStatus: "pass",
    classification: "REAL",
    markers: [],
  },
  "calendar-view": {
    id: "calendar-view",
    name: "CalendarView",
    family: "domain/scheduling",
    domain: "webui",
    lanes: ["agentping"],
    beadId: "ap-4rs.32",
    storyPath: "Catalog/WebUI/CalendarView",
    gateStatus: "pass",
    classification: "REAL",
    markers: [],
  },
  "toast-manager": {
    id: "toast-manager",
    name: "ToastManager",
    family: "foundations/feedback-status",
    domain: "webui",
    lanes: ["agentping"],
    beadId: "ap-4rs.33",
    storyPath: "Catalog/WebUI/ToastManager",
    gateStatus: "pass",
    classification: "REAL",
    markers: [],
  },
  "file-explorer": {
    id: "file-explorer",
    name: "FileExplorer",
    family: "domain/content",
    domain: "webui",
    lanes: ["agentping"],
    beadId: "ap-4rs.34",
    storyPath: "Catalog/WebUI/FileExplorer",
    gateStatus: "pass",
    classification: "REAL",
    markers: [],
  },
  "tabs": {
    id: "tabs",
    name: "Tabs",
    family: "foundations/navigation",
    domain: "webui",
    lanes: ["agentping"],
    beadId: "ap-4rs.35",
    storyPath: "Catalog/WebUI/Tabs",
    gateStatus: "pass",
    classification: "REAL",
    markers: [],
  },
  "dm-dashboard-list": {
    id: "dm-dashboard-list",
    name: "DmDashboardList",
    family: "domain/dashboard-mgr",
    domain: "dm-ui",
    lanes: ["agentping"],
    beadId: "ap-4rs.36",
    storyPath: "Catalog/DM-UI/DmDashboardList",
    gateStatus: "pass",
    classification: "REAL",
    markers: [],
  },
  "canvas-renderer": {
    id: "canvas-renderer",
    name: "CanvasRenderer",
    family: "domain/canvas",
    domain: "canvas",
    lanes: ["agentping"],
    beadId: "ap-4rs.37",
    storyPath: "Catalog/Canvas/CanvasRenderer",
    gateStatus: "pass",
    classification: "REAL",
    markers: ["runtime-coupled"],
  },
  "voice-console": {
    id: "voice-console",
    name: "VoiceConsole",
    family: "domain/media",
    domain: "webui",
    lanes: ["agentping"],
    beadId: "ap-4rs.38",
    storyPath: "Catalog/WebUI/VoiceConsole",
    gateStatus: "needs-review",
    classification: "REAL",
    markers: ["runtime-coupled"],
  },
  "entity-form": {
    id: "entity-form",
    name: "EntityForm",
    family: "domain/crud",
    domain: "webui",
    lanes: ["agentping"],
    beadId: "ap-4rs.39",
    storyPath: "Catalog/WebUI/EntityForm",
    gateStatus: "pass",
    classification: "REAL",
    markers: ["crud"],
  },

  // ---------------------------------------------------------------------------
  // SHELL COMPONENTS (5 representative)
  // ---------------------------------------------------------------------------
  "geo-map": {
    id: "geo-map",
    name: "GeoMap",
    family: "domain/system",
    domain: "webui",
    lanes: ["agentping"],
    beadId: "ap-4rs.50",
    storyPath: "Catalog/WebUI/GeoMap",
    gateStatus: "shell",
    classification: "SHELL",
    markers: [],
  },
  "video-player": {
    id: "video-player",
    name: "VideoPlayer",
    family: "domain/media",
    domain: "webui",
    lanes: ["agentping"],
    beadId: "ap-4rs.51",
    storyPath: "Catalog/WebUI/VideoPlayer",
    gateStatus: "shell",
    classification: "SHELL",
    markers: [],
  },
  "mind-map": {
    id: "mind-map",
    name: "MindMap",
    family: "domain/data-display",
    domain: "webui",
    lanes: ["agentping"],
    beadId: "ap-4rs.52",
    storyPath: "Catalog/WebUI/MindMap",
    gateStatus: "shell",
    classification: "SHELL",
    markers: [],
  },
  "pdf-preview": {
    id: "pdf-preview",
    name: "PdfPreview",
    family: "domain/content",
    domain: "webui",
    lanes: ["agentping"],
    beadId: "ap-4rs.53",
    storyPath: "Catalog/WebUI/PdfPreview",
    gateStatus: "shell",
    classification: "SHELL",
    markers: [],
  },
  "sankey-diagram": {
    id: "sankey-diagram",
    name: "SankeyDiagram",
    family: "domain/data-display",
    domain: "webui",
    lanes: ["agentping"],
    beadId: "ap-4rs.54",
    storyPath: "Catalog/WebUI/SankeyDiagram",
    gateStatus: "shell",
    classification: "SHELL",
    markers: [],
  },

  // ---------------------------------------------------------------------------
  // HOLLOW COMPONENTS (5 gallery sections)
  // ---------------------------------------------------------------------------
  "gallery-ai-section": {
    id: "gallery-ai-section",
    name: "GalleryAISection",
    family: "domain/gallery",
    domain: "webui",
    lanes: ["agentping"],
    beadId: "ap-4rs.60",
    storyPath: "Catalog/WebUI/GalleryAISection",
    gateStatus: "hollow",
    classification: "HOLLOW",
    markers: [],
  },
  "gallery-dashboard-section": {
    id: "gallery-dashboard-section",
    name: "GalleryDashboardSection",
    family: "domain/gallery",
    domain: "webui",
    lanes: ["agentping"],
    beadId: "ap-4rs.61",
    storyPath: "Catalog/WebUI/GalleryDashboardSection",
    gateStatus: "hollow",
    classification: "HOLLOW",
    markers: [],
  },
  "gallery-finance-section": {
    id: "gallery-finance-section",
    name: "GalleryFinanceSection",
    family: "domain/gallery",
    domain: "webui",
    lanes: ["agentping"],
    beadId: "ap-4rs.62",
    storyPath: "Catalog/WebUI/GalleryFinanceSection",
    gateStatus: "hollow",
    classification: "HOLLOW",
    markers: [],
  },
  "gallery-logs-section": {
    id: "gallery-logs-section",
    name: "GalleryLogsSection",
    family: "domain/gallery",
    domain: "webui",
    lanes: ["agentping"],
    beadId: "ap-4rs.63",
    storyPath: "Catalog/WebUI/GalleryLogsSection",
    gateStatus: "hollow",
    classification: "HOLLOW",
    markers: [],
  },
  "gallery-navigation-section": {
    id: "gallery-navigation-section",
    name: "GalleryNavigationSection",
    family: "domain/gallery",
    domain: "webui",
    lanes: ["agentping"],
    beadId: "ap-4rs.64",
    storyPath: "Catalog/WebUI/GalleryNavigationSection",
    gateStatus: "hollow",
    classification: "HOLLOW",
    markers: [],
  },
};

export function getComponentsByFamily(family: string): ComponentMeta[] {
  return Object.values(COMPONENT_MANIFEST).filter(
    (c) => c.family === family || c.family.startsWith(family + "/"),
  );
}

export function getComponentsByStatus(status: GateStatus): ComponentMeta[] {
  return Object.values(COMPONENT_MANIFEST).filter(
    (c) => c.gateStatus === status,
  );
}

export function getComponentsByDomain(domain: Domain): ComponentMeta[] {
  return Object.values(COMPONENT_MANIFEST).filter((c) => c.domain === domain);
}

export function getAllComponents(): ComponentMeta[] {
  return Object.values(COMPONENT_MANIFEST);
}
